[package]
name = "gcviz"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26"
rand = "0.8.5"
ratatui = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
