[package]
name = "gcviz"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26"
ratatui = "0.20"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
